version: 2.1

orbs:
  continuation: circleci/continuation@1.0.0

workflows:
  setup:
    jobs:
      - setup-job

jobs:
  setup-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Print Message
          command: echo "Triggering continuation with static config..."
          # Use the Continuation Orb to continue the pipeline
          continuation/continue:
            configuration_path: continuation-config.yml
            parameters: {}

  print-message:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print Message
          command: echo "This is a continued pipeline job!"
